### ISSUE TITLE
TypeError: render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by mweinelt** [pbucher/django-bootstrap-datepicker#16]
On Django 2.1 I get the follwing traceback when adding the DatePicker widget, while on Django 2.0 it works fine:

```pytb
Traceback (most recent call last):
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/bootstrap4/templatetags/bootstrap4.py", line 421, in bootstrap_form
    return render_form(*args, **kwargs)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/bootstrap4/forms.py", line 39, in render_form
    return renderer_cls(form, **kwargs).render()
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/bootstrap4/renderers.py", line 77, in render
    return mark_safe(self._render())
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/bootstrap4/renderers.py", line 208, in _render
    return self.render_errors() + self.render_fields()
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/bootstrap4/renderers.py", line 174, in render_fields
    bound_css_class=self.bound_css_class,
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/bootstrap4/forms.py", line 55, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/bootstrap4/renderers.py", line 77, in render
    return mark_safe(self._render())
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/bootstrap4/renderers.py", line 508, in _render
    html = self.field.as_widget(attrs=self.widget.attrs)
  File "/home/hexa/.local/share/virtualenvs/devconf3-uk6jVlS4/lib/python3.6/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
TypeError: render() got an unexpected keyword argument 'renderer'
```

**Comment by mweinelt** [comment]
Django 2.1 release notes say the following, not sure if related:

> Support for Widget.render() methods without the renderer argument is removed.

https://docs.djangoproject.com/en/2.1/releases/2.1/

**Comment by monim67** [comment]
The widget `render` method needs a `renderer` parameter, that will fix it. Please create a PR. I can't create a PR because I have detached my fork of this repository.

**Comment by pbucher** [comment]
Committed a fix for this. I haven't moved up to Django 2.1 yet so your mileage my vary on this commit.

**Comment by Permafacture** [comment]
Worked for me

**Comment by Permafacture** [comment]
It would be nice if you could push this change to pypi though

**Comment by pbucher** [comment]
Sorry for the delay. Current version has been uploaded to pypi.
